name: Gdlint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "gdtoolkit==4.*"
    - name: Analysing the code with gdlint
      run: |
        gdformat $(git ls-files '*.gd')
    - name: setup git config
      run: |
        git config user.name "zqwy01"
        git config user.email "zqwymusic@vk.com"
        
    - name: Commit to Release
      run: |
        git add -A
        git commit -a
        git push origin master
